name: Ejecutar scraper y subir CSV

on:
  schedule:
    - cron: "0 12 * * 2,5"  # Martes y viernes a las 12:00 UTC
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4 selenium webdriver-manager

      - name: Ejecutar script
        run: python scraper.py

      - name: Confirmar cambios y subir CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add jugadores_estadisticas.csv
          git commit -m "Actualizar datos de jugadores"
          git push
        continue-on-error: true
