name: Scraper Diario

on:
  schedule:
    - cron: '30 0 * * 3'  # Se ejecuta todos los martes a las 21:30 en Argentina (00:30 AM UTC del miércoles)

  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar el script
        run: python scraper.py

      - name: Subir el archivo CSV como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: jugadores_estadisticas
          path: jugadores_estadisticas.csv
